name: Tests

on: [push, pull_request]

jobs:
  test:
    container:
      image: node
    before:
      runs-on: ubuntu-latest
      steps:
        - run: echo "before"
    steps:
      - run: echo "Inside node"
